apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system
  name: solar-system-service
spec:
  type: NodePort
  selector:
    app: solar-system
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 8080
  
    
